"""Comprehensive Indian/International drug database seed data."""

DRUGS = [
    # Analgesics / Antipyretics
    ("Paracetamol","Acetaminophen","Dolo/Calpol","Analgesic/Antipyretic","500mg, 650mg, 1000mg","oral",1000),
    ("Ibuprofen","Ibuprofen","Brufen","NSAID","200mg, 400mg, 600mg","oral",900),
    ("Diclofenac","Diclofenac sodium","Voveran","NSAID","50mg, 75mg","oral/topical",800),
    ("Aceclofenac","Aceclofenac","Zerodol","NSAID","100mg","oral",750),
    ("Naproxen","Naproxen","Naprosyn","NSAID","250mg, 500mg","oral",600),
    ("Mefenamic Acid","Mefenamic Acid","Meftal","NSAID","250mg, 500mg","oral",550),
    ("Nimesulide","Nimesulide","Nise","NSAID","100mg","oral",700),
    ("Etoricoxib","Etoricoxib","Arcoxia","COX-2 inhibitor","60mg, 90mg, 120mg","oral",500),
    ("Celecoxib","Celecoxib","Celebrex","COX-2 inhibitor","100mg, 200mg","oral",450),
    ("Tramadol","Tramadol","Ultram","Opioid analgesic","50mg, 100mg","oral",400),
    ("Codeine","Codeine","Codeine Phosphate","Opioid","30mg, 60mg","oral",300),
    ("Aspirin 75mg","Acetylsalicylic acid","Ecosprin","Antiplatelet","75mg","oral",900),
    ("Aspirin 150mg","Acetylsalicylic acid","Ecosprin","Antiplatelet","150mg","oral",800),
    ("Aspirin 325mg","Acetylsalicylic acid","Disprin","Analgesic","325mg","oral",600),
    # Antibiotics
    ("Amoxicillin","Amoxicillin","Mox","Antibiotic - Penicillin","250mg, 500mg","oral",1000),
    ("Amoxicillin-Clavulanate","Amoxicillin+Clavulanate","Augmentin","Antibiotic","625mg, 1g","oral",900),
    ("Azithromycin","Azithromycin","Azee/Zithromax","Antibiotic - Macrolide","250mg, 500mg","oral",850),
    ("Clarithromycin","Clarithromycin","Klacid","Antibiotic - Macrolide","250mg, 500mg","oral",600),
    ("Ciprofloxacin","Ciprofloxacin","Ciplox","Antibiotic - Fluoroquinolone","250mg, 500mg","oral",800),
    ("Levofloxacin","Levofloxacin","Levoflox","Antibiotic - Fluoroquinolone","250mg, 500mg, 750mg","oral",750),
    ("Ofloxacin","Ofloxacin","Oflox","Antibiotic - Fluoroquinolone","200mg, 400mg","oral",600),
    ("Norfloxacin","Norfloxacin","Norflox","Antibiotic - Fluoroquinolone","400mg","oral",550),
    ("Cefixime","Cefixime","Taxim-O","Antibiotic - Cephalosporin","200mg, 400mg","oral",800),
    ("Cefuroxime","Cefuroxime","Zinnat","Antibiotic - Cephalosporin","250mg, 500mg","oral",600),
    ("Ceftriaxone","Ceftriaxone","Rocephin","Antibiotic - Cephalosporin","1g, 2g","IV/IM",700),
    ("Cephalexin","Cephalexin","Sporidex","Antibiotic - Cephalosporin","250mg, 500mg","oral",550),
    ("Doxycycline","Doxycycline","Doxt","Antibiotic - Tetracycline","100mg","oral",700),
    ("Tetracycline","Tetracycline","Hostacycline","Antibiotic","250mg, 500mg","oral",400),
    ("Metronidazole","Metronidazole","Flagyl","Antibiotic/Antiprotozoal","200mg, 400mg, 500mg","oral/IV",900),
    ("Tinidazole","Tinidazole","Tiniba","Antiprotozoal","500mg","oral",600),
    ("Cotrimoxazole","Sulfamethoxazole+Trimethoprim","Bactrim","Antibiotic","480mg, 960mg","oral",650),
    ("Nitrofurantoin","Nitrofurantoin","Macrobid","Antibiotic - UTI","50mg, 100mg","oral",500),
    ("Clindamycin","Clindamycin","Dalacin","Antibiotic","150mg, 300mg","oral",500),
    ("Erythromycin","Erythromycin","Erythrocin","Antibiotic - Macrolide","250mg, 500mg","oral",400),
    ("Vancomycin","Vancomycin","Vancocin","Antibiotic","500mg, 1g","IV",300),
    ("Meropenem","Meropenem","Meronem","Antibiotic - Carbapenem","500mg, 1g","IV",250),
    ("Piperacillin-Tazobactam","Piperacillin+Tazobactam","Piptaz","Antibiotic","4.5g","IV",300),
    ("Isoniazid","Isoniazid","INH","Antitubercular","100mg, 300mg","oral",400),
    ("Rifampicin","Rifampicin","Rimactane","Antitubercular","150mg, 300mg, 450mg, 600mg","oral",400),
    ("Ethambutol","Ethambutol","Myambutol","Antitubercular","400mg, 800mg","oral",350),
    ("Pyrazinamide","Pyrazinamide","PZA","Antitubercular","500mg, 750mg","oral",350),
    # Antifungals
    ("Fluconazole","Fluconazole","Diflucan","Antifungal","50mg, 150mg, 200mg","oral",700),
    ("Itraconazole","Itraconazole","Sporanox","Antifungal","100mg","oral",500),
    ("Ketoconazole","Ketoconazole","Nizoral","Antifungal","200mg / 2%","oral/topical",450),
    ("Terbinafine","Terbinafine","Lamisil","Antifungal","250mg / 1%","oral/topical",500),
    ("Clotrimazole","Clotrimazole","Canesten","Antifungal","1% cream","topical",550),
    ("Nystatin","Nystatin","Mycostatin","Antifungal","100,000 IU","oral/topical",350),
    ("Voriconazole","Voriconazole","Vfend","Antifungal","200mg","oral/IV",200),
    ("Amphotericin B","Amphotericin B","Fungizone","Antifungal","50mg","IV",200),
    # Antivirals
    ("Acyclovir","Acyclovir","Zovirax","Antiviral","200mg, 400mg, 800mg","oral/topical",600),
    ("Valacyclovir","Valacyclovir","Valtrex","Antiviral","500mg, 1g","oral",500),
    ("Oseltamivir","Oseltamivir","Tamiflu","Antiviral","75mg","oral",400),
    ("Remdesivir","Remdesivir","Veklury","Antiviral","100mg","IV",300),
    ("Favipiravir","Favipiravir","FabiFlu","Antiviral","200mg","oral",350),
    # Cardiovascular
    ("Amlodipine","Amlodipine","Amlodac","CCB - Antihypertensive","2.5mg, 5mg, 10mg","oral",950),
    ("Atenolol","Atenolol","Tenormin","Beta-blocker","25mg, 50mg, 100mg","oral",900),
    ("Metoprolol","Metoprolol","Betaloc","Beta-blocker","25mg, 50mg, 100mg","oral",850),
    ("Bisoprolol","Bisoprolol","Concor","Beta-blocker","2.5mg, 5mg, 10mg","oral",800),
    ("Carvedilol","Carvedilol","Dilvas","Beta-blocker","3.125mg, 6.25mg, 12.5mg, 25mg","oral",700),
    ("Losartan","Losartan","Cozaar","ARB - Antihypertensive","25mg, 50mg, 100mg","oral",900),
    ("Telmisartan","Telmisartan","Telma","ARB","40mg, 80mg","oral",850),
    ("Olmesartan","Olmesartan","Olsar","ARB","20mg, 40mg","oral",700),
    ("Valsartan","Valsartan","Diovan","ARB","80mg, 160mg","oral",650),
    ("Enalapril","Enalapril","Enam","ACE Inhibitor","2.5mg, 5mg, 10mg","oral",750),
    ("Ramipril","Ramipril","Cardace","ACE Inhibitor","1.25mg, 2.5mg, 5mg, 10mg","oral",800),
    ("Lisinopril","Lisinopril","Lisipril","ACE Inhibitor","5mg, 10mg, 20mg","oral",700),
    ("Perindopril","Perindopril","Coversyl","ACE Inhibitor","4mg, 8mg","oral",600),
    ("Hydrochlorothiazide","Hydrochlorothiazide","Esidrex","Thiazide diuretic","12.5mg, 25mg","oral",600),
    ("Furosemide","Furosemide","Lasix","Loop diuretic","20mg, 40mg, 80mg","oral/IV",800),
    ("Spironolactone","Spironolactone","Aldactone","K-sparing diuretic","25mg, 50mg, 100mg","oral",600),
    ("Torsemide","Torsemide","Dytor","Loop diuretic","10mg, 20mg","oral",500),
    ("Nitroglycerine","Nitroglycerin","Nitrostat","Antianginal","0.5mg SL","sublingual",700),
    ("Isosorbide Mononitrate","Isosorbide Mononitrate","Monotrate","Antianginal","10mg, 20mg","oral",550),
    ("Digoxin","Digoxin","Lanoxin","Cardiac glycoside","0.125mg, 0.25mg","oral",400),
    ("Clopidogrel","Clopidogrel","Plavix/Deplatt","Antiplatelet","75mg","oral",850),
    ("Ticagrelor","Ticagrelor","Brilinta","Antiplatelet","90mg","oral",500),
    ("Warfarin","Warfarin","Coumadin","Anticoagulant","1mg, 2mg, 5mg","oral",500),
    ("Heparin","Heparin","Heparin","Anticoagulant","5000 IU/mL","IV/SC",400),
    ("Enoxaparin","Enoxaparin","Lovenox","LMWH","40mg, 60mg, 80mg","SC",500),
    ("Rivaroxaban","Rivaroxaban","Xarelto","NOAC","10mg, 20mg","oral",500),
    ("Apixaban","Apixaban","Eliquis","NOAC","2.5mg, 5mg","oral",450),
    ("Dabigatran","Dabigatran","Pradaxa","NOAC","110mg, 150mg","oral",400),
    # Lipid-lowering
    ("Atorvastatin","Atorvastatin","Lipitor/Atorva","Statin","10mg, 20mg, 40mg, 80mg","oral",950),
    ("Rosuvastatin","Rosuvastatin","Crestor","Statin","5mg, 10mg, 20mg, 40mg","oral",900),
    ("Simvastatin","Simvastatin","Zocor","Statin","10mg, 20mg, 40mg","oral",700),
    ("Pravastatin","Pravastatin","Pravachol","Statin","10mg, 20mg, 40mg","oral",500),
    ("Fenofibrate","Fenofibrate","Tricor","Fibrate","145mg, 160mg","oral",500),
    ("Ezetimibe","Ezetimibe","Zetia","Cholesterol absorption inhibitor","10mg","oral",400),
    # Antidiabetics
    ("Metformin","Metformin","Glucophage","Biguanide","500mg, 850mg, 1000mg","oral",1000),
    ("Metformin SR","Metformin","Glycomet SR","Biguanide","500mg, 750mg, 1000mg","oral",900),
    ("Glibenclamide","Glibenclamide","Daonil","Sulfonylurea","2.5mg, 5mg","oral",600),
    ("Glimepiride","Glimepiride","Amaryl","Sulfonylurea","1mg, 2mg, 4mg","oral",700),
    ("Gliclazide","Gliclazide","Diamicron","Sulfonylurea","30mg, 60mg, 80mg","oral",600),
    ("Sitagliptin","Sitagliptin","Januvia","DPP-4 inhibitor","50mg, 100mg","oral",700),
    ("Vildagliptin","Vildagliptin","Galvus","DPP-4 inhibitor","50mg","oral",600),
    ("Alogliptin","Alogliptin","Nesina","DPP-4 inhibitor","6.25mg, 12.5mg, 25mg","oral",400),
    ("Empagliflozin","Empagliflozin","Jardiance","SGLT-2 inhibitor","10mg, 25mg","oral",650),
    ("Dapagliflozin","Dapagliflozin","Forxiga","SGLT-2 inhibitor","5mg, 10mg","oral",600),
    ("Canagliflozin","Canagliflozin","Invokana","SGLT-2 inhibitor","100mg, 300mg","oral",450),
    ("Liraglutide","Liraglutide","Victoza","GLP-1 agonist","0.6mg, 1.2mg, 1.8mg","SC",400),
    ("Semaglutide","Semaglutide","Ozempic","GLP-1 agonist","0.25mg, 0.5mg, 1mg","SC",350),
    ("Pioglitazone","Pioglitazone","Actos","Thiazolidinedione","15mg, 30mg, 45mg","oral",400),
    ("Insulin Regular","Regular Insulin","Actrapid","Insulin","100 IU/mL","SC/IV",800),
    ("Insulin NPH","Isophane Insulin","Insulatard","Insulin","100 IU/mL","SC",700),
    ("Insulin Glargine","Insulin Glargine","Lantus","Long-acting Insulin","100 IU/mL","SC",750),
    ("Insulin Detemir","Insulin Detemir","Levemir","Long-acting Insulin","100 IU/mL","SC",600),
    ("Insulin Aspart","Insulin Aspart","NovoRapid","Rapid-acting Insulin","100 IU/mL","SC",700),
    ("Insulin Lispro","Insulin Lispro","Humalog","Rapid-acting Insulin","100 IU/mL","SC",650),
    ("Insulin Glulisine","Insulin Glulisine","Apidra","Rapid-acting Insulin","100 IU/mL","SC",500),
    # GI / GI motility
    ("Omeprazole","Omeprazole","Omez/Prilosec","PPI","20mg, 40mg","oral/IV",1000),
    ("Pantoprazole","Pantoprazole","Pan","PPI","40mg","oral/IV",950),
    ("Rabeprazole","Rabeprazole","Razo","PPI","10mg, 20mg","oral",900),
    ("Esomeprazole","Esomeprazole","Nexium","PPI","20mg, 40mg","oral",850),
    ("Lansoprazole","Lansoprazole","Prevacid","PPI","15mg, 30mg","oral",700),
    ("Ranitidine","Ranitidine","Zantac","H2 blocker","150mg, 300mg","oral",500),
    ("Famotidine","Famotidine","Pepcid","H2 blocker","20mg, 40mg","oral",500),
    ("Domperidone","Domperidone","Domstal","Prokinetic","10mg","oral",800),
    ("Metoclopramide","Metoclopramide","Reglan","Prokinetic","5mg, 10mg","oral",700),
    ("Ondansetron","Ondansetron","Zofran","Antiemetic","4mg, 8mg","oral/IV",800),
    ("Granisetron","Granisetron","Kytril","Antiemetic","1mg, 2mg","oral",400),
    ("Loperamide","Loperamide","Imodium","Antidiarrheal","2mg","oral",600),
    ("Lactulose","Lactulose","Duphalac","Osmotic laxative","15mL, 30mL","oral",700),
    ("Bisacodyl","Bisacodyl","Dulcolax","Stimulant laxative","5mg, 10mg","oral/rectal",600),
    ("Psyllium","Ispaghula husk","Isabgol","Bulk laxative","3.4g per sachet","oral",700),
    ("Sucralfate","Sucralfate","Carafate","Mucosal protectant","500mg, 1g","oral",400),
    ("Antacid (Aluminium Hydroxide)","Aluminium Hydroxide","Gelusil","Antacid","500mg","oral",700),
    ("Simethicone","Simethicone","Gas-X","Antiflatulent","40mg, 80mg","oral",600),
    ("Hyoscine","Hyoscine Butylbromide","Buscopan","Antispasmodic","10mg","oral",700),
    ("Drotaverine","Drotaverine","No-Spa","Antispasmodic","40mg, 80mg","oral",700),
    ("Ursodeoxycholic Acid","Ursodiol","Ursocol","Hepatoprotective","150mg, 300mg","oral",400),
    ("Silymarin","Silymarin","Liv 52","Hepatoprotective","70mg","oral",600),
    ("Essentiale","Essential Phospholipids","Essentiale Forte","Hepatoprotective","300mg","oral",500),
    ("Cholestyramine","Cholestyramine","Questran","Bile acid sequestrant","4g","oral",300),
    ("Mesalamine","Mesalamine","Asacol","Aminosalicylate","400mg, 800mg","oral",400),
    # Respiratory
    ("Salbutamol","Salbutamol","Ventolin","Bronchodilator - SABA","2mg, 4mg, 100mcg inhaler","oral/inhaled",900),
    ("Levosalbutamol","Levosalbutamol","Levolin","Bronchodilator - SABA","50mcg inhaler","inhaled",700),
    ("Terbutaline","Terbutaline","Bricanyl","Bronchodilator - SABA","2.5mg, 5mg","oral",600),
    ("Salmeterol","Salmeterol","Serevent","Bronchodilator - LABA","25mcg, 50mcg inhaler","inhaled",600),
    ("Formoterol","Formoterol","Foradil","Bronchodilator - LABA","12mcg","inhaled",550),
    ("Tiotropium","Tiotropium","Spiriva","LAMA","18mcg","inhaled",700),
    ("Ipratropium","Ipratropium","Atrovent","SAMA","20mcg","inhaled",550),
    ("Budesonide","Budesonide","Pulmicort","ICS","100mcg, 200mcg, 400mcg","inhaled",750),
    ("Fluticasone","Fluticasone","Flixotide","ICS","50mcg, 125mcg, 250mcg","inhaled",700),
    ("Beclomethasone","Beclomethasone","Becotide","ICS","100mcg, 250mcg","inhaled",550),
    ("Mometasone","Mometasone","Asmanex","ICS","100mcg, 200mcg, 400mcg","inhaled",500),
    ("Ciclesonide","Ciclesonide","Alvesco","ICS","80mcg, 160mcg","inhaled",400),
    ("Theophylline","Theophylline","Theo-Dur","Xanthine","100mg, 200mg, 300mg","oral",500),
    ("Doxophylline","Doxophylline","Doxovent","Xanthine","400mg","oral",550),
    ("Aminophylline","Aminophylline","Aminophylline","Xanthine","100mg, 250mg","oral/IV",400),
    ("Montelukast","Montelukast","Singulair","LTRA","4mg, 5mg, 10mg","oral",800),
    ("Zafirlukast","Zafirlukast","Accolate","LTRA","20mg","oral",300),
    ("Guaifenesin","Guaifenesin","Mucinex","Expectorant","100mg, 200mg","oral",600),
    ("Ambroxol","Ambroxol","Mucosolvan","Mucolytic","30mg","oral",700),
    ("Bromhexine","Bromhexine","Bisolvon","Mucolytic","8mg","oral",650),
    ("Acetylcysteine","N-Acetylcysteine","Mucomyst","Mucolytic","200mg, 600mg","oral",600),
    ("Dextromethorphan","Dextromethorphan","Robitussin","Antitussive","10mg, 15mg","oral",600),
    ("Codeine Phosphate","Codeine","Linctus","Antitussive","10mg/5mL","oral",400),
    ("Chlorpheniramine","Chlorpheniramine","Piriton","Antihistamine - 1st gen","4mg","oral",700),
    ("Diphenhydramine","Diphenhydramine","Benadryl","Antihistamine - 1st gen","25mg, 50mg","oral",600),
    ("Promethazine","Promethazine","Phenergan","Antihistamine - 1st gen","10mg, 25mg","oral",600),
    ("Cetirizine","Cetirizine","Zyrtec","Antihistamine - 2nd gen","5mg, 10mg","oral",900),
    ("Loratadine","Loratadine","Claritin","Antihistamine - 2nd gen","10mg","oral",850),
    ("Fexofenadine","Fexofenadine","Allegra","Antihistamine - 2nd gen","60mg, 120mg, 180mg","oral",800),
    ("Levocetirizine","Levocetirizine","Xyzal","Antihistamine - 2nd gen","2.5mg, 5mg","oral",750),
    ("Desloratadine","Desloratadine","Clarinex","Antihistamine - 2nd gen","5mg","oral",650),
    ("Bilastine","Bilastine","Bilaxa","Antihistamine - 2nd gen","20mg","oral",500),
    ("Rupatadine","Rupatadine","Rupanex","Antihistamine - 2nd gen","10mg","oral",450),
    # CNS / Neurology
    ("Pregabalin","Pregabalin","Lyrica","Anticonvulsant/Neuropathic","25mg, 75mg, 150mg, 300mg","oral",800),
    ("Gabapentin","Gabapentin","Neurontin","Anticonvulsant/Neuropathic","100mg, 300mg, 400mg","oral",750),
    ("Phenytoin","Phenytoin","Dilantin","Anticonvulsant","50mg, 100mg","oral",400),
    ("Carbamazepine","Carbamazepine","Tegretol","Anticonvulsant","100mg, 200mg, 400mg","oral",500),
    ("Valproic Acid","Valproate sodium","Depakote","Anticonvulsant","200mg, 500mg","oral",500),
    ("Levetiracetam","Levetiracetam","Keppra","Anticonvulsant","250mg, 500mg, 1000mg","oral",500),
    ("Lamotrigine","Lamotrigine","Lamictal","Anticonvulsant","25mg, 50mg, 100mg","oral",450),
    ("Topiramate","Topiramate","Topamax","Anticonvulsant","25mg, 50mg, 100mg","oral",400),
    ("Clonazepam","Clonazepam","Rivotril","Benzodiazepine/Anticonvulsant","0.25mg, 0.5mg, 1mg, 2mg","oral",600),
    ("Diazepam","Diazepam","Valium","Benzodiazepine","2mg, 5mg, 10mg","oral/IV",500),
    ("Alprazolam","Alprazolam","Xanax","Benzodiazepine","0.25mg, 0.5mg, 1mg","oral",600),
    ("Lorazepam","Lorazepam","Ativan","Benzodiazepine","0.5mg, 1mg, 2mg","oral/IV",500),
    ("Zolpidem","Zolpidem","Ambien","Sedative-hypnotic","5mg, 10mg","oral",500),
    ("Zopiclone","Zopiclone","Imovane","Sedative-hypnotic","3.75mg, 7.5mg","oral",450),
    ("Sertraline","Sertraline","Zoloft","SSRI","25mg, 50mg, 100mg","oral",800),
    ("Escitalopram","Escitalopram","Lexapro","SSRI","5mg, 10mg, 20mg","oral",800),
    ("Fluoxetine","Fluoxetine","Prozac","SSRI","10mg, 20mg, 40mg","oral",750),
    ("Paroxetine","Paroxetine","Paxil","SSRI","10mg, 20mg","oral",600),
    ("Fluvoxamine","Fluvoxamine","Luvox","SSRI","50mg, 100mg","oral",450),
    ("Citalopram","Citalopram","Celexa","SSRI","10mg, 20mg, 40mg","oral",600),
    ("Venlafaxine","Venlafaxine","Effexor","SNRI","37.5mg, 75mg, 150mg","oral",650),
    ("Duloxetine","Duloxetine","Cymbalta","SNRI","20mg, 30mg, 60mg","oral",700),
    ("Amitriptyline","Amitriptyline","Elavil","TCA","10mg, 25mg, 50mg, 75mg","oral",700),
    ("Nortriptyline","Nortriptyline","Pamelor","TCA","10mg, 25mg","oral",500),
    ("Imipramine","Imipramine","Tofranil","TCA","10mg, 25mg, 75mg","oral",400),
    ("Mirtazapine","Mirtazapine","Remeron","NaSSA","7.5mg, 15mg, 30mg","oral",550),
    ("Bupropion","Bupropion","Wellbutrin","NDRI","100mg, 150mg, 300mg","oral",500),
    ("Quetiapine","Quetiapine","Seroquel","Atypical antipsychotic","25mg, 50mg, 100mg, 200mg","oral",600),
    ("Olanzapine","Olanzapine","Zyprexa","Atypical antipsychotic","2.5mg, 5mg, 10mg","oral",600),
    ("Risperidone","Risperidone","Risperdal","Atypical antipsychotic","0.5mg, 1mg, 2mg, 4mg","oral",550),
    ("Aripiprazole","Aripiprazole","Abilify","Atypical antipsychotic","5mg, 10mg, 15mg, 20mg","oral",500),
    ("Haloperidol","Haloperidol","Haldol","Typical antipsychotic","0.5mg, 1mg, 5mg","oral/IM",400),
    ("Clozapine","Clozapine","Clozaril","Atypical antipsychotic","25mg, 100mg","oral",350),
    ("Lithium","Lithium carbonate","Eskalith","Mood stabilizer","300mg","oral",400),
    ("Donepezil","Donepezil","Aricept","Cholinesterase inhibitor","5mg, 10mg","oral",450),
    ("Memantine","Memantine","Namenda","NMDA antagonist","5mg, 10mg","oral",400),
    ("Levodopa+Carbidopa","Levodopa/Carbidopa","Sinemet","Antiparkinsonian","100/25mg, 250/25mg","oral",400),
    ("Pramipexole","Pramipexole","Mirapex","Dopamine agonist","0.125mg, 0.25mg, 1mg","oral",350),
    ("Ropinirole","Ropinirole","Requip","Dopamine agonist","0.25mg, 0.5mg, 1mg","oral",300),
    ("Trihexyphenidyl","Trihexyphenidyl","Artane","Anticholinergic","2mg","oral",300),
    ("Sumatriptan","Sumatriptan","Imitrex","Triptan (Migraine)","50mg, 100mg","oral",500),
    ("Rizatriptan","Rizatriptan","Maxalt","Triptan (Migraine)","5mg, 10mg","oral",450),
    ("Topiramate 25mg","Topiramate","Topamax","Migraine prophylaxis","25mg","oral",400),
    ("Propranolol","Propranolol","Inderal","Beta-blocker/Migraine","10mg, 20mg, 40mg, 80mg","oral",700),
    # Endocrinology / Thyroid
    ("Levothyroxine","Levothyroxine","Synthroid/Eltroxin","Thyroid hormone","25mcg, 50mcg, 75mcg, 100mcg","oral",900),
    ("Carbimazole","Carbimazole","Neo-Mercazole","Antithyroid","5mg, 20mg","oral",400),
    ("Propylthiouracil","Propylthiouracil","PTU","Antithyroid","50mg","oral",350),
    ("Methimazole","Methimazole","Tapazole","Antithyroid","5mg, 10mg","oral",350),
    ("Prednisolone","Prednisolone","Wysolone","Corticosteroid","5mg, 10mg, 20mg, 40mg","oral",900),
    ("Methylprednisolone","Methylprednisolone","Medrol","Corticosteroid","4mg, 8mg, 16mg","oral/IV",800),
    ("Dexamethasone","Dexamethasone","Decadron","Corticosteroid","0.5mg, 4mg, 8mg","oral/IV",800),
    ("Hydrocortisone","Hydrocortisone","Cortef","Corticosteroid","5mg, 10mg, 20mg / 1%","oral/topical/IV",700),
    ("Betamethasone","Betamethasone","Celestone","Corticosteroid","0.1%, 0.05%","topical",600),
    ("Triamcinolone","Triamcinolone","Kenalog","Corticosteroid","0.1%","topical/IM",500),
    ("Fludrocortisone","Fludrocortisone","Florinef","Mineralocorticoid","0.1mg","oral",300),
    # Rheumatology / Musculoskeletal
    ("Methotrexate","Methotrexate","Rheumatrex","DMARD","2.5mg, 5mg, 10mg, 15mg, 20mg","oral",500),
    ("Hydroxychloroquine","Hydroxychloroquine","Plaquenil","DMARD","200mg, 400mg","oral",600),
    ("Leflunomide","Leflunomide","Arava","DMARD","10mg, 20mg","oral",400),
    ("Sulfasalazine","Sulfasalazine","Azulfidine","DMARD","500mg","oral",450),
    ("Colchicine","Colchicine","Colchicine","Antigout","0.5mg, 1mg","oral",600),
    ("Allopurinol","Allopurinol","Zyloprim","Xanthine oxidase inhibitor","100mg, 300mg","oral",700),
    ("Febuxostat","Febuxostat","Feburic","Xanthine oxidase inhibitor","40mg, 80mg","oral",500),
    ("Probenecid","Probenecid","Benemid","Uricosuric","500mg","oral",300),
    ("Calcium + Vit D3","Calcium Carbonate + Cholecalciferol","Shelcal","Mineral supplement","500mg+250IU","oral",900),
    ("Calcium Citrate","Calcium Citrate","Citracal","Mineral supplement","250mg","oral",600),
    ("Alendronate","Alendronate sodium","Fosamax","Bisphosphonate","10mg, 70mg","oral",500),
    ("Risedronate","Risedronate","Actonel","Bisphosphonate","5mg, 35mg","oral",450),
    ("Zoledronic Acid","Zoledronate","Zometa","Bisphosphonate","4mg/5mL","IV",300),
    ("Calcitonin","Calcitonin","Miacalcin","Calcium regulator","200 IU","nasal/SC",300),
    ("Denosumab","Denosumab","Prolia","RANK-L inhibitor","60mg","SC",300),
    ("Teriparatide","Teriparatide","Forteo","PTH analogue","20mcg","SC",250),
    ("Diclofenac Gel","Diclofenac","Voveran Gel","Topical NSAID","1%, 2%","topical",700),
    ("Methocarbamol","Methocarbamol","Robaxin","Muscle relaxant","500mg, 750mg","oral",400),
    ("Cyclobenzaprine","Cyclobenzaprine","Flexeril","Muscle relaxant","5mg, 10mg","oral",400),
    ("Baclofen","Baclofen","Lioresal","Muscle relaxant","5mg, 10mg","oral",500),
    ("Tizanidine","Tizanidine","Zanaflex","Muscle relaxant","2mg, 4mg","oral",450),
    ("Eperisone","Eperisone","Myonal","Muscle relaxant","50mg, 150mg","oral",500),
    # Nephrology
    ("Calcium Acetate","Calcium Acetate","Phoslyra","Phosphate binder","667mg","oral",300),
    ("Sevelamer","Sevelamer","Renagel","Phosphate binder","400mg, 800mg","oral",350),
    ("Erythropoietin","Epoetin alfa","Epogen","ESA","2000IU, 4000IU","SC/IV",300),
    ("Darbepoetin","Darbepoetin alfa","Aranesp","ESA","25mcg, 40mcg","SC/IV",300),
    ("Sodium Bicarbonate","Sodium Bicarbonate","NaHCO3","Alkalizing agent","500mg, 1g","oral",400),
    ("Lacidipine","Lacidipine","Motens","CCB","2mg, 4mg","oral",350),
    # Haematology
    ("Iron Sulfate","Ferrous Sulfate","Fersolate","Iron supplement","200mg (65mg elemental iron)","oral",700),
    ("Iron Sucrose","Iron Sucrose","Venofer","IV Iron","100mg/5mL","IV",400),
    ("Ferric Carboxymaltose","Ferric Carboxymaltose","Injectafer","IV Iron","500mg/10mL","IV",350),
    ("Vitamin B12","Cyanocobalamin","Mecobalamin","Vitamin","500mcg, 1000mcg","oral/IM",800),
    ("Folic Acid","Folic acid","Folvite","Vitamin","0.4mg, 1mg, 5mg","oral",900),
    ("Vitamin D3","Cholecalciferol","D-Rise","Vitamin","60,000 IU","oral",850),
    ("Hydroxocobalamin","Hydroxocobalamin","Hydroxocobalamin","Vitamin B12","1000mcg/mL","IM",400),
    ("Hemocoagulase","Hemocoagulase","Reptilase","Hemostatic","1U","IV/IM",400),
    ("Tranexamic Acid","Tranexamic Acid","Cyklokapron","Antifibrinolytic","250mg, 500mg","oral/IV",500),
    ("Filgrastim","G-CSF","Neupogen","Colony stimulating factor","300mcg","SC/IV",250),
    # Vitamins / Supplements
    ("Multivitamin","Multivitamin","Revital","Supplement","1 tablet","oral",900),
    ("Vitamin C","Ascorbic acid","Celin","Vitamin","250mg, 500mg","oral",800),
    ("Vitamin E","Tocopherol","Evion","Vitamin","200mg, 400mg","oral",600),
    ("Vitamin A","Retinol","Vit A","Vitamin","50,000 IU","oral",500),
    ("Zinc Sulfate","Zinc Sulfate","Zincovit","Mineral","10mg, 20mg","oral",700),
    ("Magnesium Oxide","Magnesium","Mag Ox","Mineral","400mg","oral",500),
    ("ORS Sachet","Oral Rehydration Salts","Electral","Rehydration","1 sachet in 1L","oral",800),
    ("Potassium Chloride","KCl","Kaon","Electrolyte","600mg, 750mg","oral",400),
    ("Normal Saline","Sodium Chloride 0.9%","NS","IV Fluid","1L, 500mL","IV",800),
    ("Ringer Lactate","Lactated Ringer","RL","IV Fluid","1L, 500mL","IV",700),
    ("Dextrose 5%","Dextrose 5% in Water","D5W","IV Fluid","1L, 500mL","IV",700),
    # Antiparasitic
    ("Albendazole","Albendazole","Albenza","Antihelminthic","400mg","oral",600),
    ("Mebendazole","Mebendazole","Vermox","Antihelminthic","100mg, 500mg","oral",550),
    ("Ivermectin","Ivermectin","Stromectol","Antiparasitic","3mg, 6mg, 12mg","oral",500),
    ("Chloroquine","Chloroquine","Aralen","Antimalarial","150mg, 250mg","oral",500),
    ("Artemether-Lumefantrine","Artemether+Lumefantrine","Coartem","Antimalarial","20/120mg","oral",400),
    ("Artesunate","Artesunate","Artesun","Antimalarial","60mg, 120mg","oral/IV",350),
    ("Doxycycline 100mg","Doxycycline","Doryx","Antimalarial prophylaxis","100mg","oral",550),
    ("Primaquine","Primaquine","Primaquine","Antimalarial","2.5mg, 7.5mg","oral",350),
    # Dermatology
    ("Mupirocin","Mupirocin","Bactroban","Topical antibiotic","2%","topical",600),
    ("Fusidic Acid","Fusidic Acid","Fucidin","Topical antibiotic","2%","topical",500),
    ("Tretinoin","Tretinoin","Retin-A","Retinoid","0.025%, 0.05%, 0.1%","topical",500),
    ("Adapalene","Adapalene","Differin","Retinoid","0.1%, 0.3%","topical",500),
    ("Benzoyl Peroxide","Benzoyl Peroxide","Benzac","Acne treatment","2.5%, 5%, 10%","topical",600),
    ("Clindamycin 1% Gel","Clindamycin","Clindac A","Topical antibiotic","1%","topical",600),
    ("Hydroquinone","Hydroquinone","Melanex","Depigmenting agent","2%, 4%","topical",400),
    ("Azelaic Acid","Azelaic Acid","Azelex","Acne/Rosacea","15%, 20%","topical",400),
    ("Minoxidil","Minoxidil","Rogaine","Hair growth","2%, 5%","topical",600),
    ("Finasteride","Finasteride","Propecia","5-alpha reductase inhibitor","1mg, 5mg","oral",550),
    ("Isotretinoin","Isotretinoin","Accutane","Retinoid","5mg, 10mg, 20mg","oral",400),
    ("Permethrin","Permethrin","Elimite","Antiparasitic","5%","topical",500),
    ("Lindane","Lindane","Kwell","Antiparasitic","1%","topical",350),
    ("Tacrolimus","Tacrolimus","Protopic","Calcineurin inhibitor","0.03%, 0.1%","topical",400),
    ("Pimecrolimus","Pimecrolimus","Elidel","Calcineurin inhibitor","1%","topical",400),
    ("Calcipotriol","Calcipotriol","Dovonex","Vitamin D analogue","0.005%","topical",400),
    ("Coal Tar","Coal Tar","Pentrax","Antipsoriatic","1%, 2%, 5%","topical",350),
    # Ophthalmology
    ("Ciprofloxacin Eye Drops","Ciprofloxacin","Ciloxan","Antibiotic eye drops","0.3%","ophthalmic",600),
    ("Tobramycin Eye Drops","Tobramycin","Tobrex","Antibiotic eye drops","0.3%","ophthalmic",500),
    ("Chloramphenicol Eye Drops","Chloramphenicol","Chloromycetin","Antibiotic eye drops","0.5%","ophthalmic",500),
    ("Gentamicin Eye Drops","Gentamicin","Garamycin","Antibiotic eye drops","0.3%","ophthalmic",450),
    ("Timolol Eye Drops","Timolol","Timoptic","Antiglaucoma","0.25%, 0.5%","ophthalmic",500),
    ("Latanoprost","Latanoprost","Xalatan","Antiglaucoma - Prostaglandin","0.005%","ophthalmic",400),
    ("Brimonidine","Brimonidine","Alphagan","Antiglaucoma - Alpha agonist","0.1%, 0.15%","ophthalmic",400),
    ("Dorzolamide","Dorzolamide","Trusopt","Antiglaucoma - CAI","2%","ophthalmic",400),
    ("Prednisolone Eye Drops","Prednisolone","Pred Forte","Steroid eye drops","1%","ophthalmic",500),
    ("Artificial Tears","Hydroxypropyl Methylcellulose","Refresh","Lubricant eye drops","0.3%, 0.5%","ophthalmic",700),
    ("Olopatadine","Olopatadine","Patanol","Antiallergic eye drops","0.1%, 0.2%","ophthalmic",500),
    ("Atropine Sulfate","Atropine","Isopto Atropine","Mydriatic","1%","ophthalmic",400),
    # ENT
    ("Xylometazoline","Xylometazoline","Otrivin","Decongestant nasal spray","0.05%, 0.1%","nasal",700),
    ("Oxymetazoline","Oxymetazoline","Afrin","Decongestant nasal spray","0.05%","nasal",600),
    ("Mometasone Nasal Spray","Mometasone","Nasonex","Corticosteroid nasal spray","50mcg","nasal",700),
    ("Fluticasone Nasal Spray","Fluticasone","Flonase","Corticosteroid nasal spray","50mcg","nasal",650),
    ("Azelastine","Azelastine","Astelin","Antihistamine nasal spray","137mcg","nasal",450),
    ("Ciprofloxacin Ear Drops","Ciprofloxacin","Ciprodex","Antibiotic ear drops","0.3%","otic",500),
    ("Clotrimazole Ear Drops","Clotrimazole","Canesten","Antifungal ear drops","1%","otic",400),
    # Women's Health
    ("Oral Contraceptive (Combined)","Ethinylestradiol+Levonorgestrel","Loette","Oral contraceptive","0.02mg/0.1mg","oral",600),
    ("Progesterone","Progesterone","Prometrium","Progestogen","100mg, 200mg, 400mg","oral/vaginal",500),
    ("Medroxyprogesterone","Medroxyprogesterone","Provera","Progestogen","5mg, 10mg","oral",500),
    ("Clomiphene","Clomiphene","Clomid","Fertility","25mg, 50mg, 100mg","oral",400),
    ("Oxytocin","Oxytocin","Pitocin","Uterotonic","5 IU/mL","IV/IM",350),
    ("Misoprostol","Misoprostol","Cytotec","Prostaglandin","25mcg, 200mcg","oral/vaginal",400),
    ("Mifepristone","Mifepristone","Korlym","Antiprogestogen","200mg","oral",300),
    ("Bromocriptine","Bromocriptine","Parlodel","Dopamine agonist","2.5mg","oral",350),
    ("Cabergoline","Cabergoline","Dostinex","Dopamine agonist","0.5mg","oral",400),
    # Miscellaneous / Emergency
    ("Epinephrine","Adrenaline","EpiPen","Sympathomimetic","1mg/mL, 0.3mg/0.3mL","IM/IV",600),
    ("Atropine","Atropine Sulfate","Atropine","Anticholinergic","0.6mg/mL","IV/IM",400),
    ("Naloxone","Naloxone","Narcan","Opioid antagonist","0.4mg/mL","IV/IM/nasal",400),
    ("Flumazenil","Flumazenil","Romazicon","Benzodiazepine antagonist","0.1mg/mL","IV",300),
    ("Activated Charcoal","Activated charcoal","CharcoAid","Antidote","25g, 50g","oral",400),
    ("N-Acetylcysteine","N-Acetylcysteine","Mucomyst","Antidote (paracetamol)","200mg, 600mg","oral/IV",500),
    ("Glucagon","Glucagon","GlucaGen","Hyperglycemic agent","1mg","SC/IM",350),
    ("Dextrose 50%","50% Dextrose","D50","Hyperglycemia antidote","50mL","IV",600),
    ("Vitamin K1","Phytonadione","Mephyton","Vitamin","10mg","oral/IV",400),
    ("Pralidoxime","Pralidoxime","2-PAM","Antidote (organophosphate)","500mg","IV/IM",250),
    ("Sodium Thiosulfate","Sodium Thiosulfate","Sodium Thiosulfate","Antidote (cyanide)","250mg/mL","IV",200),
    ("Dextran 40","Dextran 40","Rheomacrodex","Plasma expander","10%","IV",350),
    ("Albumin","Human Albumin","Albumin","Plasma protein","20%, 25%","IV",400),
]

def get_seed_drugs():
    return DRUGS
